branch-defaults:
  default:
    environment: Prod-env-1
environment-defaults:
  Prod-env-1:
    branch: null
    repository: null
global:
  application_name: prod
  default_ec2_keyname: new_key
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
