branch-defaults:
  main:
    environment: Prod-env-1
global:
  application_name: prod
  branch: null
  default_ec2_keyname: new_key
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
