version: '3.9'

services:
  app:
    build: .
    ports:
      - "4000:4000" # Expose the app on port 3000
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on its default port
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on its default port

volumes:
  mongo_data: